config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :invoice_clients
  resources :invoice_suppliers
  resources :rols
  resources :add_to_invoice_clients
  resources :add_to_invoice_suppliers
  resources :users
  resources :roles
  resources :clients
  resources :suppliers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/invoice_client.rb
class InvoiceClient < ApplicationRecord
  belongs_to :Id_Product
end

app/controllers/invoice_clients_controller.rb
class InvoiceClientsController < ApplicationController
  before_action :set_invoice_client, only: [:show, :edit, :update, :destroy]

  # GET /invoice_clients
  # GET /invoice_clients.json
  def index
    @invoice_clients = InvoiceClient.all
  end

  # GET /invoice_clients/1
  # GET /invoice_clients/1.json
  def show
  end

  # GET /invoice_clients/new
  def new
    @invoice_client = InvoiceClient.new
  end

  # GET /invoice_clients/1/edit
  def edit
  end

  # POST /invoice_clients
  # POST /invoice_clients.json
  def create
    @invoice_client = InvoiceClient.new(invoice_client_params)

    respond_to do |format|
      if @invoice_client.save
        format.html { redirect_to @invoice_client, notice: 'Invoice client was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_client }
      else
        format.html { render :new }
        format.json { render json: @invoice_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_clients/1
  # PATCH/PUT /invoice_clients/1.json
  def update
    respond_to do |format|
      if @invoice_client.update(invoice_client_params)
        format.html { redirect_to @invoice_client, notice: 'Invoice client was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_client }
      else
        format.html { render :edit }
        format.json { render json: @invoice_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_clients/1
  # DELETE /invoice_clients/1.json
  def destroy
    @invoice_client.destroy
    respond_to do |format|
      format.html { redirect_to invoice_clients_url, notice: 'Invoice client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_client
      @invoice_client = InvoiceClient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invoice_client_params
      params.require(:invoice_client).permit(:Id_Invoice_Client, :Client_Id, :Id_Product_id, :Net_Value, :Brute_Value, :IVA)
    end
end

app/helpers/invoice_clients_helper.rb
module InvoiceClientsHelper
end

app/views/invoice_clients/_form.html.erb
<%= form_with(model: invoice_client, local: true) do |form| %>
  <% if invoice_client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(invoice_client.errors.count, "error") %> prohibited this invoice_client from being saved:</h2>

      <ul>
      <% invoice_client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Id_Invoice_Client %>
    <%= form.text_field :Id_Invoice_Client %>
  </div>

  <div class="field">
    <%= form.label :Client_Id %>
    <%= form.text_field :Client_Id %>
  </div>

  <div class="field">
    <%= form.label :Id_Product_id %>
    <%= form.text_field :Id_Product_id %>
  </div>

  <div class="field">
    <%= form.label :Net_Value %>
    <%= form.number_field :Net_Value %>
  </div>

  <div class="field">
    <%= form.label :Brute_Value %>
    <%= form.text_field :Brute_Value %>
  </div>

  <div class="field">
    <%= form.label :IVA %>
    <%= form.text_field :IVA %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/invoice_clients/edit.html.erb
<h1>Editing Invoice Client</h1>

<%= render 'form', invoice_client: @invoice_client %>

<%= link_to 'Show', @invoice_client %> |
<%= link_to 'Back', invoice_clients_path %>

app/views/invoice_clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Invoice Clients</h1>

<table>
  <thead>
    <tr>
      <th>Id invoice client</th>
      <th>Client id</th>
      <th>Id product</th>
      <th>Net value</th>
      <th>Brute value</th>
      <th>Iva</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_clients.each do |invoice_client| %>
      <tr>
        <td><%= invoice_client.Id_Invoice_Client %></td>
        <td><%= invoice_client.Client_Id %></td>
        <td><%= invoice_client.Id_Product %></td>
        <td><%= invoice_client.Net_Value %></td>
        <td><%= invoice_client.Brute_Value %></td>
        <td><%= invoice_client.IVA %></td>
        <td><%= link_to 'Show', invoice_client %></td>
        <td><%= link_to 'Edit', edit_invoice_client_path(invoice_client) %></td>
        <td><%= link_to 'Destroy', invoice_client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice Client', new_invoice_client_path %>

app/views/invoice_clients/new.html.erb
<h1>New Invoice Client</h1>

<%= render 'form', invoice_client: @invoice_client %>

<%= link_to 'Back', invoice_clients_path %>

app/views/invoice_clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id invoice client:</strong>
  <%= @invoice_client.Id_Invoice_Client %>
</p>

<p>
  <strong>Client id:</strong>
  <%= @invoice_client.Client_Id %>
</p>

<p>
  <strong>Id product:</strong>
  <%= @invoice_client.Id_Product %>
</p>

<p>
  <strong>Net value:</strong>
  <%= @invoice_client.Net_Value %>
</p>

<p>
  <strong>Brute value:</strong>
  <%= @invoice_client.Brute_Value %>
</p>

<p>
  <strong>Iva:</strong>
  <%= @invoice_client.IVA %>
</p>

<%= link_to 'Edit', edit_invoice_client_path(@invoice_client) %> |
<%= link_to 'Back', invoice_clients_path %>