config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :invoice_clients
  resources :invoice_suppliers
  resources :rols
  resources :add_to_invoice_clients
  resources :add_to_invoice_suppliers
  resources :users
  resources :roles
  resources :clients
  resources :suppliers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/add_to_invoice_supplier.rb
class AddToInvoiceSupplier < ApplicationRecord
  belongs_to :Document_ID
  belongs_to :Product_Id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyed_price.rb
class BuyedPrice < ApplicationRecord
  belongs_to :product_id
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/invoice_client.rb
class InvoiceClient < ApplicationRecord
  belongs_to :Id_Product
end

app/models/invoice_supplier.rb
class InvoiceSupplier < ApplicationRecord
  belongs_to :Id_Product
end

app/models/rol.rb
class Rol < ApplicationRecord
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/sale_price.rb
class SalePrice < ApplicationRecord
  belongs_to :Product_id
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :Product_id
end

app/models/supplier.rb
class Supplier < ApplicationRecord
end

app/models/supplier_price.rb
class SupplierPrice < ApplicationRecord
  belongs_to :Id_Supplier
  belongs_to :Product_Id
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/add_to_invoice_suppliers_controller.rb
class AddToInvoiceSuppliersController < ApplicationController
  before_action :set_add_to_invoice_supplier, only: [:show, :edit, :update, :destroy]

  # GET /add_to_invoice_suppliers
  # GET /add_to_invoice_suppliers.json
  def index
    @add_to_invoice_suppliers = AddToInvoiceSupplier.all
  end

  # GET /add_to_invoice_suppliers/1
  # GET /add_to_invoice_suppliers/1.json
  def show
  end

  # GET /add_to_invoice_suppliers/new
  def new
    @add_to_invoice_supplier = AddToInvoiceSupplier.new
  end

  # GET /add_to_invoice_suppliers/1/edit
  def edit
  end

  # POST /add_to_invoice_suppliers
  # POST /add_to_invoice_suppliers.json
  def create
    @add_to_invoice_supplier = AddToInvoiceSupplier.new(add_to_invoice_supplier_params)

    respond_to do |format|
      if @add_to_invoice_supplier.save
        format.html { redirect_to @add_to_invoice_supplier, notice: 'Add to invoice supplier was successfully created.' }
        format.json { render :show, status: :created, location: @add_to_invoice_supplier }
      else
        format.html { render :new }
        format.json { render json: @add_to_invoice_supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /add_to_invoice_suppliers/1
  # PATCH/PUT /add_to_invoice_suppliers/1.json
  def update
    respond_to do |format|
      if @add_to_invoice_supplier.update(add_to_invoice_supplier_params)
        format.html { redirect_to @add_to_invoice_supplier, notice: 'Add to invoice supplier was successfully updated.' }
        format.json { render :show, status: :ok, location: @add_to_invoice_supplier }
      else
        format.html { render :edit }
        format.json { render json: @add_to_invoice_supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /add_to_invoice_suppliers/1
  # DELETE /add_to_invoice_suppliers/1.json
  def destroy
    @add_to_invoice_supplier.destroy
    respond_to do |format|
      format.html { redirect_to add_to_invoice_suppliers_url, notice: 'Add to invoice supplier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_add_to_invoice_supplier
      @add_to_invoice_supplier = AddToInvoiceSupplier.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def add_to_invoice_supplier_params
      params.require(:add_to_invoice_supplier).permit(:Document_ID_id, :Product_Id_id, :Quantity, :Previous_Quantity, :Post_Quantity)
    end
end

app/controllers/rols_controller.rb
class RolsController < ApplicationController
  before_action :set_rol, only: [:show, :edit, :update, :destroy]

  # GET /rols
  # GET /rols.json
  def index
    @rols = Rol.all
  end

  # GET /rols/1
  # GET /rols/1.json
  def show
  end

  # GET /rols/new
  def new
    @rol = Rol.new
  end

  # GET /rols/1/edit
  def edit
  end

  # POST /rols
  # POST /rols.json
  def create
    @rol = Rol.new(rol_params)

    respond_to do |format|
      if @rol.save
        format.html { redirect_to @rol, notice: 'Rol was successfully created.' }
        format.json { render :show, status: :created, location: @rol }
      else
        format.html { render :new }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rols/1
  # PATCH/PUT /rols/1.json
  def update
    respond_to do |format|
      if @rol.update(rol_params)
        format.html { redirect_to @rol, notice: 'Rol was successfully updated.' }
        format.json { render :show, status: :ok, location: @rol }
      else
        format.html { render :edit }
        format.json { render json: @rol.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rols/1
  # DELETE /rols/1.json
  def destroy
    @rol.destroy
    respond_to do |format|
      format.html { redirect_to rols_url, notice: 'Rol was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rol
      @rol = Rol.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rol_params
      params.require(:rol).permit(:Id_rol, :Type)
    end
end

app/helpers/add_to_invoice_suppliers_helper.rb
module AddToInvoiceSuppliersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rols_helper.rb
module RolsHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/add_to_invoice_suppliers/_form.html.erb
<%= form_with(model: add_to_invoice_supplier, local: true) do |form| %>
  <% if add_to_invoice_supplier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(add_to_invoice_supplier.errors.count, "error") %> prohibited this add_to_invoice_supplier from being saved:</h2>

      <ul>
      <% add_to_invoice_supplier.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Document_ID_id %>
    <%= form.text_field :Document_ID_id %>
  </div>

  <div class="field">
    <%= form.label :Product_Id_id %>
    <%= form.text_field :Product_Id_id %>
  </div>

  <div class="field">
    <%= form.label :Quantity %>
    <%= form.text_field :Quantity %>
  </div>

  <div class="field">
    <%= form.label :Previous_Quantity %>
    <%= form.text_field :Previous_Quantity %>
  </div>

  <div class="field">
    <%= form.label :Post_Quantity %>
    <%= form.text_field :Post_Quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/add_to_invoice_suppliers/edit.html.erb
<h1>Editing Add To Invoice Supplier</h1>

<%= render 'form', add_to_invoice_supplier: @add_to_invoice_supplier %>

<%= link_to 'Show', @add_to_invoice_supplier %> |
<%= link_to 'Back', add_to_invoice_suppliers_path %>

app/views/add_to_invoice_suppliers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Add To Invoice Suppliers</h1>

<table>
  <thead>
    <tr>
      <th>Document id</th>
      <th>Product id</th>
      <th>Quantity</th>
      <th>Previous quantity</th>
      <th>Post quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @add_to_invoice_suppliers.each do |add_to_invoice_supplier| %>
      <tr>
        <td><%= add_to_invoice_supplier.Document_ID %></td>
        <td><%= add_to_invoice_supplier.Product_Id %></td>
        <td><%= add_to_invoice_supplier.Quantity %></td>
        <td><%= add_to_invoice_supplier.Previous_Quantity %></td>
        <td><%= add_to_invoice_supplier.Post_Quantity %></td>
        <td><%= link_to 'Show', add_to_invoice_supplier %></td>
        <td><%= link_to 'Edit', edit_add_to_invoice_supplier_path(add_to_invoice_supplier) %></td>
        <td><%= link_to 'Destroy', add_to_invoice_supplier, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Add To Invoice Supplier', new_add_to_invoice_supplier_path %>

app/views/add_to_invoice_suppliers/new.html.erb
<h1>New Add To Invoice Supplier</h1>

<%= render 'form', add_to_invoice_supplier: @add_to_invoice_supplier %>

<%= link_to 'Back', add_to_invoice_suppliers_path %>

app/views/add_to_invoice_suppliers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document id:</strong>
  <%= @add_to_invoice_supplier.Document_ID %>
</p>

<p>
  <strong>Product id:</strong>
  <%= @add_to_invoice_supplier.Product_Id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @add_to_invoice_supplier.Quantity %>
</p>

<p>
  <strong>Previous quantity:</strong>
  <%= @add_to_invoice_supplier.Previous_Quantity %>
</p>

<p>
  <strong>Post quantity:</strong>
  <%= @add_to_invoice_supplier.Post_Quantity %>
</p>

<%= link_to 'Edit', edit_add_to_invoice_supplier_path(@add_to_invoice_supplier) %> |
<%= link_to 'Back', add_to_invoice_suppliers_path %>